sudo: false
language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
rust:
  - stable
  - beta
  - nightly
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - travis-cargo build
  - travis-cargo test
  - travis-cargo --only stable doc
after_success:
  - travis-cargo --only stable doc-upload
  - travis-cargo coveralls --no-sudo --verify
env:
  global:
    - secure: NaYk9xXQKTTRESUrQ1XK6UjSE1T8lv9Xphtoux9b2vZvziuECUXv/aelpobSmI8nheO9V+ZVgMbskParMCuRiAjUPEA2wh0w66nn9wVeR8ZD7bVltXEkcNCtRO3NoOQmSyyClbEAQdn04YazfdDqZ1Sor260J1u04D1c4LD+dD/2YKS+VnrGtHPa2NBx5ebFu0YTFxMAQez6KhPy3V5zPCCSWMIu7d/s5K9NNg6JlHqz06KQ1ZVKpV6ZRV5OA/16B5elLMpH+8PDO70LyWnSBYtdAn68epydjXEmZh3ra94bQz7U5K4XdnwhBp0PljIlY9LE6YbDxvU+ZcwX0VIpLCMStTV7xpbr7wI45OmNKaNLXZiBGHezsaVUSVRFCJZ7EB/xYDDk+9CIev6LlGR9wSFD1VnjHN1lo8X9tTN2rH7o0csnr1AkjJM8U46M8Mh/7+luGeAlwxkH5UQW/GnogZbF+UIHpSLayM04qECSz7C3fBhAVXW9H/20QxMCzNWDbKDpi8KIXbEq4AGSYCDrMwJRdQ182QtZzjBdnSvRENE2jsy33lpUxBGd/sYB4dy2FjkUGf+cjiS9F/CDRHDo4vNlYpXJvZ9aaqgjaEd5nIlw4aBwVWN4Qaf/iXbxiL9wg+RIGRhCsaKkxEgWaFRb1Y8s9zJ9B51wQsGBLHyorOs=
    - RUST_BACKTRACE=1
