[package]
name = "robotparser"
version = "0.2.0"
authors = ["messense <messense@icloud.com>"]
description = "robots.txt parser for Rust"
repository = "https://github.com/messense/robotparser-rs"
homepage = "https://github.com/messense/robotparser-rs"
readme = "README.md"
keywords = ["robot", "robots", "parser", "spider", "crawler"]
license = "MIT"

[dependencies]
hyper = "*"
url = "*"
time = "*"

[features]
unstable = []
