[package]
authors = ["messense <messense@icloud.com>"]
description = "robots.txt parser for Rust"
homepage = "https://github.com/messense/robotparser-rs"
keywords = ["robot", "robots", "parser", "spider", "crawler"]
license = "MIT"
name = "robotparser"
readme = "README.md"
repository = "https://github.com/messense/robotparser-rs"
version = "0.4.0"

[dependencies]
hyper = "0.7"
time = "0.1"
url = "0.5"

[features]
unstable = []
