[package]
authors = ["messense <messense@icloud.com>"]
description = "robots.txt parser for Rust"
documentation = "https://messense.github.io/robotparser-rs"
homepage = "https://github.com/messense/robotparser-rs"
keywords = ["robot", "robots", "parser", "spider", "crawler"]
license = "MIT"
name = "robotparser"
readme = "README.md"
repository = "https://github.com/messense/robotparser-rs"
version = "0.4.3"

[dependencies]
hyper = "0.9"
time = "0.1"
url = "1.0"

[dependencies.clippy]
optional = true
version = "^0.*"

[features]
unstable = []
